package Entity;
// Generated 21-Oct-2016 10:02:56 by Hibernate Tools 4.3.1



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String username;
     private String password;
     private String hoten;
     private boolean gioitinh;
     private String email;
     private boolean role;

    public Customer() {
    }

    public Customer(String username, String password, String hoten, boolean gioitinh, String email, boolean role) {
       this.username = username;
       this.password = password;
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.email = email;
       this.role = role;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public boolean isGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(boolean gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isRole() {
        return this.role;
    }
    
    public void setRole(boolean role) {
        this.role = role;
    }




}


