package Entity;
// Generated 21-Oct-2016 10:02:56 by Hibernate Tools 4.3.1



/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     private String maKhachHang;
     private String hoTen;
     private String matKhau;
     private String email;
     private String sdt;

    public Khachhang() {
    }

    public Khachhang(String maKhachHang, String hoTen, String matKhau, String email, String sdt) {
       this.maKhachHang = maKhachHang;
       this.hoTen = hoTen;
       this.matKhau = matKhau;
       this.email = email;
       this.sdt = sdt;
    }
   
    public String getMaKhachHang() {
        return this.maKhachHang;
    }
    
    public void setMaKhachHang(String maKhachHang) {
        this.maKhachHang = maKhachHang;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    public String getUsername() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String getgioitinh() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


