package Entity;
// Generated 21-Oct-2016 10:02:56 by Hibernate Tools 4.3.1



/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private String code;
     private String name;
     private float price;

    public Products() {
    }

    public Products(String code, String name, float price) {
       this.code = code;
       this.name = name;
       this.price = price;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }




}


